apiVersion: batch/v1
kind: Job
metadata:
  generateName: deploy-at-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: pre-sync-container
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              #!/bin/sh
              START_DEPLOY_MSG="Application Deployment Start"

              echo "Time Zone: ${TZ}"
              echo "Current time: $(date)"
              echo "Deployment Start Time: ${DEPLOYMENT_TIME}"

              # Validate DEPLOYMENT_TIME format
              if ! [[ $DEPLOYMENT_TIME =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}\ [0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
                  echo "Error: Invalid DEPLOYMENT_TIME format. Expected format: YYYY-MM-DD HH:MM:SS" >&2
                  exit 2
              fi

              # Calculate the time difference in seconds
              sec_diff=$(($(date -d "$DEPLOYMENT_TIME" "+%s") - $(date "+%s")))

              if ((sec_diff <= 0)); then
                  echo "${START_DEPLOY_MSG}"
                  exit 0
              fi
              echo "Time difference in seconds: $sec_diff"
              sleep "$sec_diff"
              echo "${START_DEPLOY_MSG}"
              exit 0
          env:
            - name: TZ
              value: Asia/Hong_Kong
            - name: DEPLOYMENT_TIME
              value: '2024-06-05 15:25:00'
      restartPolicy: Never
  backoffLimit: 0